import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def generate_report_pdf(user_name: str, profile: dict, report_text: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="CustomSubtitle", fontSize=12, leading=16, spaceAfter=12, textColor=colors.HexColor("#4B79A1")))
    styles.add(ParagraphStyle(name="CustomSectionHeading", parent=styles["Heading2"], spaceAfter=8, textColor=colors.HexColor("#333333")))
    styles.add(ParagraphStyle(name="CustomBody", parent=styles["Normal"], fontSize=10.5, leading=15, spaceAfter=6))
    styles.add(ParagraphStyle(name="CustomBullet", parent=styles["CustomBody"], leftIndent=12, bulletIndent=6, bulletFontName="Helvetica", bulletFontSize=10))

    story = []

    story.append(Paragraph("SheStarts AI Career Report", styles["Title"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"User: {user_name}", styles["CustomSubtitle"]))
    story.append(Paragraph("Generated by SheStarts AI Career Counselor", styles["CustomBody"]))
    story.append(Spacer(1, 18))

    if profile:
        story.append(Paragraph("Career Plan Summary", styles["CustomSectionHeading"]))
        summary_data = [
            ["Field", "Value"],
            ["Career Goal", profile.get("career_goal", "Not provided")],
            ["Preferred Job Type", profile.get("preferred_job_type", "Not provided")],
            ["Preferred Location", profile.get("preferred_location", "Not provided")],
            ["Highest Education", profile.get("highest_education", "Not provided")],
            ["Previous Role", profile.get("previous_job_role", "Not provided")],
            ["Industry", profile.get("industry", "Not provided")],
            ["Years of Experience", str(profile.get("years_of_experience", "0"))],
            ["Career Gap", str(profile.get("career_gap_years", "0")) + " years"],
            ["Study Hours / Day", str(profile.get("study_hours_per_day", "0"))],
        ]

        table = Table(summary_data, hAlign="LEFT", colWidths=[160, 340])
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4B79A1")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 11),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                ("BOX", (0, 0), (-1, -1), 0.75, colors.grey),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ])
        )
        story.append(table)
        story.append(Spacer(1, 20))

    if report_text:
        story.append(Paragraph("AI Career Report", styles["CustomSectionHeading"]))
        story.append(Spacer(1, 6))

        lines = [line.strip() for line in report_text.splitlines() if line.strip()]
        block = []
        for line in lines:
            if line.startswith("-"):
                if block:
                    story.append(Paragraph(" ".join(block), styles["CustomBody"]))
                    block = []
                bullet_text = line.lstrip("- ")
                story.append(ListFlowable([ListItem(Paragraph(bullet_text, styles["CustomBullet"]), bulletColor=colors.black)], bulletType="bullet", start="bullet"))
            elif line.startswith("###") or line.startswith("##"):
                if block:
                    story.append(Paragraph(" ".join(block), styles["CustomBody"]))
                    block = []
                heading_text = line.lstrip("# ")
                story.append(Spacer(1, 8))
                story.append(Paragraph(heading_text, styles["Heading3"]))
                story.append(Spacer(1, 4))
            else:
                block.append(line)

        if block:
            story.append(Paragraph(" ".join(block), styles["CustomBody"]))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
